
package servicios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Mon Sep 02 12:34:43 CEST 2019
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "registrarApuesta", namespace = "http://servicios/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarApuesta", namespace = "http://servicios/", propOrder = {"arg0", "arg1"})

public class RegistrarApuesta {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private double arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

}

