
package servicios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Mon Sep 02 12:34:43 CEST 2019
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "registrarApuestaResponse", namespace = "http://servicios/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarApuestaResponse", namespace = "http://servicios/")

public class RegistrarApuestaResponse {


}

