
package servicios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Mon Sep 02 16:59:06 CEST 2019
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "resolverApuestasResponse", namespace = "http://servicios/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resolverApuestasResponse", namespace = "http://servicios/")

public class ResolverApuestasResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

