
package servicios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Tue Sep 03 10:00:10 CEST 2019
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "registrarCompraResponse", namespace = "http://servicios/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarCompraResponse", namespace = "http://servicios/")

public class RegistrarCompraResponse {


}

