
package servicios.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.2
 * Tue Sep 03 10:00:10 CEST 2019
 * Generated source version: 2.6.2
 */

@XmlRootElement(name = "registrarCompra", namespace = "http://servicios/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registrarCompra", namespace = "http://servicios/")

public class RegistrarCompra {

    @XmlElement(name = "arg0")
    private servicios.Ordenador arg0;

    public servicios.Ordenador getArg0() {
        return this.arg0;
    }

    public void setArg0(servicios.Ordenador newArg0)  {
        this.arg0 = newArg0;
    }

}

